// Copyright (C) RenZhai.2021.All Rights Reserved.

#pragma once
#include "../SimpleProtocolsDefinition.h"

DEFINITION_SIMPLE_PROTOCOLS(Hello,1024)
DEFINITION_SIMPLE_PROTOCOLS(Challenge, 1025)
DEFINITION_SIMPLE_PROTOCOLS(Login, 1026)
DEFINITION_SIMPLE_PROTOCOLS(Welcom, 1027)
DEFINITION_SIMPLE_PROTOCOLS(Join, 1028)

DEFINITION_SIMPLE_PROTOCOLS(Debug, 1029)
DEFINITION_SIMPLE_PROTOCOLS(Failure, 1030)
DEFINITION_SIMPLE_PROTOCOLS(Upgrade, 1031)

DEFINITION_SIMPLE_PROTOCOLS(HeartBeat, 1032)
DEFINITION_SIMPLE_PROTOCOLS_FORCE(Close, 1033)


DEFINITION_SIMPLE_PROTOCOLS(HandshaketoSend, 1034)
DEFINITION_SIMPLE_PROTOCOLS(ReadytoAccept, 1035)
DEFINITION_SIMPLE_PROTOCOLS(Send, 1036)
DEFINITION_SIMPLE_PROTOCOLS(Recv, 1037)
DEFINITION_SIMPLE_PROTOCOLS(RecvComplete, 1038)
